# Generated by Django 2.2.24 on 2025-07-02 20:29

from django.db import migrations


def create_owners_from_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        if flat.owner or flat.owners_phonenumber or flat.owner_pure_phone:
            Owner.objects.get_or_create(
                full_name=flat.owner,
                phone=flat.owners_phonenumber,
                pure_phone=flat.owner_pure_phone
            )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250702_0135'),
    ]

    operations = [
        migrations.RunPython(create_owners_from_flats),
    ]
