# Generated by Django 2.2.24 on 2025-07-02 22:14

from django.db import migrations


def owners_and_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        owners = Owner.objects.filter(
            full_name=flat.owner,
            phone=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )
        for owner in owners:
            owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_migrate_owners_from_flat'),
    ]

    operations = [
        migrations.RunPython(owners_and_flats),
    ]
