# Generated by Django 2.2.24 on 2025-07-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_link_flats_to_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
