# Generated by Django 2.2.24 on 2025-07-04 14:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20250704_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', unique=True, verbose_name='Нормализованный номер'),
        ),
    ]
